# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on, from https://github.com/coq-community/docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.11'
          - dev
        ocaml_version: ['4.07-flambda']
      fail-fast: false  # don't stop jobs if one fails
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#       - uses: coq-community/docker-coq-action@v1
#         with:
#           opam_file: 'folder/coq-proj.opam'
#           coq_version: ${{ matrix.coq_version }}
#           ocaml_version: ${{ matrix.ocaml_version }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: make all
